# https://taskfile.dev

version: '3'

dotenv:
  - example.env

tasks:
  create-ca:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-ca $CANAME

  create-server:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-server $SERVERNAME

  create-client:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-client $CLIENTNAME

  run-server:
    cmds:
      - docker run --rm -v $PWD/config:/etc/openvpn -v $PWD/server.conf:/etc/openvpn/openvpn.conf tillhoff/openvpn
  
  run-client:
    cmds:
      - docker run --rm -v $PWD/config:/etc/openvpn -v $PWD/client.conf:/etc/openvpn/openvpn.conf tillhoff/openvpn
