# https://taskfile.dev

version: '3'

dotenv:
  - example.env

tasks:

  setup:
    cmds:
      - task: set-ip
      - task: create-ca
      - task: create-server
      - task: create-client

  create-ca:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-ca $CANAME

  create-server:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-server $SERVERNAME

  create-client:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-client $CLIENTNAME

  run-server:
    cmds:
      - docker run --rm -v $PWD/config:/etc/openvpn -v $PWD/server.conf:/etc/openvpn/openvpn.conf tillhoff/openvpn
  
  run-client:
    cmds:
      - docker run --rm -v $PWD/config:/etc/openvpn -v $PWD/client.conf:/etc/openvpn/openvpn.conf tillhoff/openvpn openvpn -remote <address> <port> <proto> /etc/openvpn/openvpn.conf

  set-ip:
    cmds:
      - sed -i "s|^local.*|local $(curl ipinfo.io/ip)|" server.conf
      - sed -i "s|^remote.*|remote $(curl ipinfo.io/ip) 1194|" client.conf