# https://taskfile.dev

version: '3'

dotenv:
  - example.env

tasks:
  create-ca:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) --env EASYRSA_REQ_CN=$CANAME tillhoff/openvpn create-ca

  create-server:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-server $SERVERNAME

  create-client:
    cmds:
      - docker run -it --rm -v $PWD/config:/etc/openvpn --user $(id -u):$(id -g) tillhoff/openvpn create-client $CLIENTNAME
